import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "BMR BlogApp Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="container mt-4" >
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
